[package]
name = "rust-voice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }

cpal = "0.13.5"
anyhow = "1.0.62"
ringbuf = "0.2.8"

serde = {version = "1", features = ["derive"]}
bincode = "1"

log = "0.4.17"
env_logger = "0.9.0"